In [1]:
import pandas as pd
import numpy as np
import pycaret
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split  # For splitting data
from sklearn.preprocessing import StandardScaler, MinMaxScaler  # For scaling
from sklearn.impute import SimpleImputer  # For handling missing values
from sklearn.preprocessing import OneHotEncoder, LabelEncoder  # For encoding categorical data

In [5]:
# Atur tampilan agar semua kolom ditampilkan
pd.set_option('display.max_columns', None)

In [6]:
df = pd.read_csv("C:\\Users\\ICT\\gemastik_ginal\\train.csv")
df

,id,Pendapatan Keluarga,Jumlah Tanggungan dalam Keluarga,Pekerjaan Orang Tua/Wali,Pendidikan Orang Tua/Wali,Kepemilikan Aset,Lokasi Tempat Tinggal,Pengeluaran Bulanan Keluarga,Status Kepesertaan Program Bantuan Pemerintah,Riwayat Beasiswa atau Bantuan Pendidikan,Ayah Hidup?,Ibu Hidup?,Status Kepemilikan Tempat Tinggal,Jumlah (Perkiraan Harga Pasar) Kendaraan yang Dimiliki,Daya Listrik (Watt),Luas Tanah Rumah (m2),Luas Bangunan Rumah (m2),NJOP per Meter,Bahan Atap Rumah,Bahan Tembok Rumah,Bahan Lantai Rumah,Rerata Pengeluaran Listrik & Air per Bulan,Total Hutang,Cicilan Hutang per Bulan,Program Studi,Kota,Jalur Masuk,Golongan UKT
0,127748,Rp 1.000.000 s.d. Rp 2.000.000,2.0,Tidak Bekerja,SLTA Sederajat,Milik Sendiri,Kab. Sragen,500000.0,KIS/JKS/BPJS,KIPK,Meninggal,Hidup,Milik Sendiri,2.0,900.0,144.0,126.0,103.0,genting,semen,keramik,450000.0,0.0,0.0,Ilmu Politik,Kab. Sragen,SNBT,0.0
1,90205,lebih dari Rp 5.000.000,2.0,Buruh,SLTA Sederajat,Milik Sendiri,Kabupaten Tangerang,3500000.0,KIS/JKS/BPJS,Tidak Ada,Hidup,Hidup,Milik Sendiri,6500000.0,900.0,60.0,22.0,128.0,Genteng,Batako Plester,Keramik,320000.0,45000000.0,4500000.0,Geografi,Kabupaten Tangerang,SNBP,3.0
2,82795,Rp 3.000.000 s.d. Rp 4.000.000,2.0,Wiraswasta,SD,Milik Sendiri,Kabupaten Grobogan,600000.0,KIS/JKS/BPJS,Tidak,Hidup,Hidup,Milik Sendiri,20000000.0,450.0,586.0,65.0,128000.0,Genting,Batu Bata,Keramik,NaN,0.0,0.0,Ilmu Politik,Kabupaten Grobogan,SNBT,4.0
3,108947,lebih dari Rp 5.000.000,2.0,Wiraswasta,SLTP,Milik Sendiri,Kab. Bogor,2250000.0,KIS/JKS/BPJS,Tidak Dapat,Hidup,Hidup,Milik Sendiri,8000000.0,900.0,93.0,70.0,2176000.0,Kayu dan asbes,Bata merah dan hebel,Keramik,500000.0,0.0,0.0,Pendidikan Ekonomi,Kab. Bogor,SNBT,5.0
4,89985,Rp 3.000.000 s.d. Rp 4.000.000,NaN,Wiraswasta,MTs,Milik Sendiri,Kabupaten Pemalang,2310000.0,KIS/JKS/BPJS,Tidak Dapat,Hidup,Hidup,Milik Sendiri,1000000.0,900.0,0.0,57.0,0.0,"Genting tanah liat, asbes, dan seng.",Batu bata,"Keramik, tegel, plester.",105000.0,5000000.0,500000.0,Pendidikan Teknik Elektro,Kabupaten Pemalang,SNBP,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30375,147514,Rp 1.000.000 s.d. Rp 2.000.000,0.0,Buruh,SLTA,Menumpang,Kab. Boyolali,500000.0,KIS/JKS/BPJS,kipk,Hidup,Hidup,Menumpang,18000000.0,900.0,2700.0,90.0,160000.0,Genting,Batu bata/ bata merah,Plaster,60000.0,26000000.0,1447000.0,Geografi,Kab. Boyolali,SNBP,0.0
30376,62832,"kurang dari Rp 1.000.000,-",0.0,Buruh,MI,Milik Sendiri,Kabupaten Kudus,600000.0,NaN,KIPK,Hidup,Hidup,Milik Sendiri,1000000.0,450.0,142.0,42.0,36000.0,Genting,Semen,Batu bata,62084.0,2000000.0,160000.0,Pendidikan Bahasa Perancis,Kabupaten Kudus,SNBP,0.0
30377,88943,"kurang dari Rp 1.000.000,-",3.0,Petani,SLTA Sederajat,Milik Sendiri,Kabupaten Tuban,450000.0,KIS/JKS/BPJS,kipk,Hidup,Hidup,Milik Sendiri,3000000.0,450.0,450.0,40.0,20000.0,Genting tanah liat,Kayu,Tanah,0.0,0.0,0.0,Pendidikan Fisika,Kabupaten Tuban,SNBP,0.0
30378,149599,"kurang dari Rp 1.000.000,-",1.0,Buruh,SMP,Milik Sendiri,Kab. Pekalongan,450000.0,KIS/JKS/BPJS,KIPK,Hidup,Meninggal,Milik Sendiri,6000000.0,450.0,310.0,40.0,64000.0,Genteng,Batu bata,Keramik dan tanah,68500.0,0.0,0.0,Pendidikan Guru Sekolah Dasar,Kab. Pekalongan,SNBT,0.0
30379,82699,Rp 2.000.000 s.d. Rp 3.000.000,2.0,Buruh,SLTA Sederajat,Milik Sendiri,Kabupaten Pati,1100000.0,KIS/JKS/BPJS,kipk,Hidup,Hidup,Milik Sendiri,4500000.0,450.0,441.0,54.0,27000.0,genting,batu bata,keramik,50000.0,0.0,0.0,Pendidikan Sejarah,Kabupaten Pati,SNBT,0.0

In [8]:
from pycaret.classification import *

In [9]:
clf = setup(data=df, target='Golongan UKT', session_id=123)

In [10]:
best_model = compare_models()

In [11]:
gbc = create_model('gbc')

In [13]:
tuned_rf = tune_model(gbc)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [14]:
evaluate_model(tuned_rf)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…